services:
  app:
    build: .
    command: bash start.sh
    restart: on-failure
    network_mode: "host"
    volumes:
      - ./cfg:/opt/JDownloader/cfg
      - ./tools:/JDownloader/tools
#added Volumes 
